### ISSUE TITLE
[FE] UI 스펙 및 뷰 구현

### ISSUE THREAD

**Issue by kakasoo** [forest-membership/non-block-king#7]
## 💡 이슈 내용
유저가 시각적으로 확인할 수 있는 페이지 및 인터페이스를 구현한다.

## ✅ 작업 내용

- [x] 메인 뷰 구현
- [x] 모드 뷰 구현
- [ ] 게임 뷰(& 대기 뷰) 구현
    - [ ] 1 대 1 랜덤 매칭
    - [ ] 1 대 다 랜덤 매칭
    - [ ] 친구 초대 매칭

## 🚨 주의 사항
- 다 사용자를 고려하여야 한다.
- 싱글 페이지 기반으로 구현한다.

**Comment by sohnjunior** [comment]
하위 이슈로 분리하여 close 합니다.

**Comment by sohnjunior** [comment]
하위 이슈로 분리하여 close 합니다.
